#########
# CORE
#########

twistlock:
  enabled: false

clusterAuditor:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

monitoring:
  enabled: true

gatekeeper:
  enabled: false

jaeger:
  enabled: false

kiali:
  enabled: true

istiooperator:
  enabled: true

eckoperator:
  enabled: false


#########
# ADDONS
#########
addons:
  gitlab:
    enabled: false
    