#########
# CORE
#########

twistlock:
  enabled: false

clusterAuditor:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

gatekeeper:
  enabled: false

istiooperator:
  enabled: true

eckoperator:
  enabled: false


#########
# ADDONS
#########
addons:
  gitlab:
    enabled: false
    