apiVersion: v1
kind: Namespace
metadata:
  name: dependencytrack
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dependencytrack
  namespace: dependencytrack
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/dependency-track.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dependencytrack
  namespace: dependencytrack
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: dependencytrack
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: common
  dependsOn:
  - name: bigbang
    namespace: bigbang
  - name: istio
    namespace: bigbang