domain: dependencytrack.bigbang.dev

replicaCount: 3

service:
  type: NodePort

redis:
  enabled: false

frontend:
  env:
  - name: API_BASE_URL
    value: "https://dependencytrack-api.bigbang.dev"
# tls:
#   enabled: true

# certificate:
#   create: true
